### ISSUE TITLE
what does the result means in the examples ?   

### ISSUE THREAD

**Issue by AsmaML** [ChongYou/subspace-clustering#2]
hello ?

could you please explaine me what the array result refere to ?

**Comment by AsmaML** [comment]
i understant now the mecanisme of the clustering , 
now my question is :

i have a list of ndarrays , and i need to cluster these vectors ? can i do it with this tools please? and how? or do you have any idea ?

**Comment by ChongYou** [comment]
Hi AsmaZbt, for a list of arrays, you may want to gather them into a single array as an input to the functions here.
