### ISSUE TITLE
Question on implementation of least_squares_subspace_clustering

### ISSUE THREAD

**Issue by lizhenstat** [ChongYou/subspace-clustering#5]
Hi, thanks for sharing the python version of your great work! I have on related question on the implementation of the function [least_squares_subspace_clustering](https://github.com/ChongYou/subspace-clustering/blob/master/cluster/selfrepresentation.py#505).
I notice the input X is of dimension [N,D] while in paper X is of dimension [D,N], but I did not understand why the implementation
is the same as Equation-(18) in the paper?
```python
tmp = np.linalg.solve(np.matmul(X.T, X) + np.eye(n_features) / gamma, X.T) # [d,n]
return np.matmul(X, tmp).T # [n,n]
```
Thanks for your time and any help would be appreciated!

**Comment by ChongYou** [comment]
The code corresponds to applying matrix inversion lemma to Eq. (18) in the paper.
